// Canvas drawing helpers.
//
// Everything the app shows is HTML and SVG; a shareable image is neither. There
// is no dependency-free way to photograph a DOM node — html2canvas is a
// dependency, and the usual trick of wrapping HTML in an <svg><foreignObject>
// and rasterising it does not work in WebKit at all, which is the only browser
// this app runs in on the phone it was built for. So the card is *drawn*, on a
// canvas, with these primitives.
//
// The one visual the card cannot draw by hand is the body map. Those shapes are
// already vectors, so `loadPaths` reads the same two SVG files the app renders
// inline and turns them into Path2D objects the canvas can fill directly — no
// image rasterisation, no data URLs, no WebKit quirks, and full control over the
// colour of every region.

const FAMILY = '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", system-ui, sans-serif';

export const font = (size, weight = 400) => `${weight} ${size}px ${FAMILY}`;

/* ============================ shapes ============================ */

/** ctx.roundRect is Safari 16+; this keeps the card working on older phones. */
export function roundRect(ctx, x, y, w, h, r) {
  const rad = Math.min(r, w / 2, h / 2);
  ctx.beginPath();
  ctx.moveTo(x + rad, y);
  ctx.arcTo(x + w, y, x + w, y + h, rad);
  ctx.arcTo(x + w, y + h, x, y + h, rad);
  ctx.arcTo(x, y + h, x, y, rad);
  ctx.arcTo(x, y, x + w, y, rad);
  ctx.closePath();
}

export function fillRound(ctx, x, y, w, h, r, fill) {
  roundRect(ctx, x, y, w, h, r);
  ctx.fillStyle = fill;
  ctx.fill();
}

export function strokeRound(ctx, x, y, w, h, r, stroke, width = 1) {
  roundRect(ctx, x, y, w, h, r);
  ctx.strokeStyle = stroke;
  ctx.lineWidth = width;
  ctx.stroke();
}

/* ============================= text ============================= */

/**
 * @param o {size, weight, color, align, baseline, track, max}
 *   `track` is letter spacing in px, drawn glyph by glyph — ctx.letterSpacing
 *   is too new to rely on, and the uppercase keys need it to look right.
 *   `max` truncates with an ellipsis rather than overflowing the card.
 * @returns the width actually drawn
 */
export function drawText(ctx, str, x, y, o = {}) {
  const {
    size = 14, weight = 400, color = '#EAF0FA',
    align = 'left', baseline = 'alphabetic', track = 0, max = null,
  } = o;

  ctx.font = font(size, weight);
  ctx.textBaseline = baseline;
  ctx.fillStyle = color;

  let s = String(str);
  if (max !== null) s = fitText(ctx, s, max, track);

  const w = widthOf(ctx, s, track);
  const startX = align === 'right' ? x - w : align === 'center' ? x - w / 2 : x;

  if (!track) {
    ctx.textAlign = 'left';
    ctx.fillText(s, startX, y);
    return w;
  }

  ctx.textAlign = 'left';
  let cx = startX;
  for (const ch of s) {
    ctx.fillText(ch, cx, y);
    cx += ctx.measureText(ch).width + track;
  }
  return w;
}

export function widthOf(ctx, str, track = 0) {
  const base = ctx.measureText(str).width;
  return track ? base + track * Math.max(0, [...String(str)].length - 1) : base;
}

/** Measure without drawing. Sets ctx.font as a side effect, like drawText. */
export function textWidth(ctx, str, { size = 14, weight = 400, track = 0 } = {}) {
  ctx.font = font(size, weight);
  return widthOf(ctx, String(str), track);
}

function fitText(ctx, str, max, track) {
  if (widthOf(ctx, str, track) <= max) return str;
  let s = str;
  while (s.length > 1 && widthOf(ctx, `${s}…`, track) > max) s = s.slice(0, -1);
  return `${s}…`;
}

/** Greedy word wrap. Returns the lines; the caller decides where they go. */
export function wrapLines(ctx, str, max, { size = 13, weight = 400 } = {}) {
  ctx.font = font(size, weight);
  const words = String(str).split(/\s+/).filter(Boolean);
  const lines = [];
  let line = '';
  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (line && ctx.measureText(next).width > max) {
      lines.push(line);
      line = word;
    } else {
      line = next;
    }
  }
  if (line) lines.push(line);
  return lines;
}

/* =========================== svg paths =========================== */

const artCache = new Map();

/**
 * Read an SVG of flat <path> elements into Path2D objects.
 *
 * Deliberately narrow: it understands the two body-map files and nothing else.
 * Those are generated by tools/build_bodymap.py and are guaranteed to be plain
 * paths with a viewBox — no transforms, no groups that matter, no gradients. A
 * general SVG renderer would be a library, and this app does not take those.
 */
export async function loadPaths(url) {
  if (artCache.has(url)) return artCache.get(url);

  const job = (async () => {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${url}: ${res.status}`);
    const doc = new DOMParser().parseFromString(await res.text(), 'image/svg+xml');
    const svg = doc.querySelector('svg');
    if (!svg) throw new Error(`${url} has no <svg>`);

    const [, , vw, vh] = (svg.getAttribute('viewBox') || '0 0 100 100')
      .split(/[\s,]+/).map(Number);

    const paths = [];
    for (const node of doc.querySelectorAll('path')) {
      const d = node.getAttribute('d');
      if (!d) continue;
      paths.push({
        path: new Path2D(d),
        region: node.getAttribute('data-region'),
        muscle: (node.getAttribute('class') || '').includes('muscle'),
      });
    }
    return { width: vw, height: vh, paths };
  })();

  artCache.set(url, job);
  // A failed fetch must not poison the cache — the next attempt should retry.
  job.catch(() => artCache.delete(url));
  return job;
}

/**
 * Draw loaded paths into a box of a given width, keeping the aspect ratio.
 *
 * @param fillFor  region key -> colour, or null to leave it unlit
 * @returns the height the drawing took
 */
export function drawPaths(ctx, art, x, y, width, opts = {}) {
  const {
    fillFor = () => null,
    baseFill = '#17223A',
    baseStroke = '#223049',
    unlitFill = '#17223A',
    glow = 0,
  } = opts;

  const scale = width / art.width;
  ctx.save();
  ctx.translate(x, y);
  ctx.scale(scale, scale);
  // Stroke widths in the source are in user units (the viewBox is 35 x 93), so
  // they scale with the transform exactly as they do in the inline SVG.
  ctx.lineWidth = 0.12;
  ctx.lineJoin = 'round';

  for (const p of art.paths) {
    if (!p.muscle) {
      ctx.fillStyle = baseFill;
      ctx.fill(p.path);
      ctx.strokeStyle = baseStroke;
      ctx.stroke(p.path);
    }
  }

  for (const p of art.paths) {
    if (!p.muscle) continue;
    const fill = fillFor(p.region);
    // Shadow blur is in device pixels regardless of the transform, so it is set
    // by the caller in output units rather than derived from `scale`.
    ctx.shadowBlur = fill && glow ? glow : 0;
    ctx.shadowColor = fill || 'transparent';
    ctx.fillStyle = fill || unlitFill;
    ctx.fill(p.path);
    ctx.shadowBlur = 0;
    ctx.strokeStyle = 'rgba(10, 14, 26, .8)';
    ctx.stroke(p.path);
  }

  ctx.restore();
  return art.height * scale;
}
